"""the scientific name, beside the common one

`plants.species` holds the *common* name and always has — `DiagnosisState.species_name`
returns `SpeciesGuess.common_name` — so the binomial the vision model produced, and
Pl@ntNet corroborated, had nowhere to go and was discarded on every diagnosis. The visible
symptom was two identical lines on every plant: its name, and the same string beneath it in
the italics a scientific name would have used.

Nullable and **not backfilled**, because nothing can be backfilled from: the scientific
name was never written anywhere, not even onto the diagnosis that found it. Existing plants
carry no binomial until they are diagnosed again, and the screens show nothing rather than
guessing one from the common name.


Revision ID: 139fad2ecae2
Revises: 1fadc82b9276
Create Date: 2026-09-07 14:03:35.465061

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy  # noqa: F401 — generated Vector() columns reference it
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139fad2ecae2'
down_revision: Union[str, Sequence[str], None] = '1fadc82b9276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('species_scientific', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'species_scientific')
    # ### end Alembic commands ###
