"""partial usage on runs

Somewhere durable for what a run's earlier passes spent. A diagnosis pauses at the
clarifying-question interrupt, and the pass that resumes it has its own collector in its
own worker thread — so the pass that finishes could only ever report its own half, and
the vision and gate calls in the first half were never recorded at all. The pause can
outlive the process, so memory was not an option.

Nullable and unbackfilled: existing rows spent what they spent and no figure for them
exists to write.

Revision ID: 1fadc82b9276
Revises: a1c7e2f90b34
Create Date: 2026-09-07 10:22:12.056149

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy  # noqa: F401 — generated Vector() columns reference it
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fadc82b9276'
down_revision: Union[str, Sequence[str], None] = 'a1c7e2f90b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('partial_usage_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'partial_usage_json')
    # ### end Alembic commands ###
