"""account roles

Revision ID: 28ce41499bec
Revises: 3e920a86b0fa
Create Date: 2026-08-26 10:34:50.590534

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy  # noqa: F401 — generated Vector() columns reference it
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ce41499bec'
down_revision: Union[str, Sequence[str], None] = '3e920a86b0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # A server default, not only the ORM's. Autogenerate wrote this as a bare NOT NULL
    # column, which fails outright on a table that already has rows — and the default is
    # worth keeping afterwards, so that a row written by a repair script or a later
    # migration gets a valid role rather than violating the constraint below.
    op.add_column(
        "users",
        sa.Column("role", sa.String(length=32), nullable=False, server_default="member"),
    )
    op.create_check_constraint("ck_users_role", "users", "role IN ('member', 'admin')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_role', 'users', type_='check')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
