"""corpus chunks

Revision ID: 67f6ce1daf6d
Revises: e5069a658630
Create Date: 2026-08-25 14:45:33.316136

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f6ce1daf6d'
down_revision: Union[str, Sequence[str], None] = 'e5069a658630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The corpus table has a vector column, so the extension has to exist first. Stated
    # here rather than assumed of the image: a managed Postgres is provisioned empty,
    # and "run CREATE EXTENSION by hand once" is exactly the deployment step that gets
    # forgotten.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus_chunks',
    sa.Column('doc_id', sa.Text(), nullable=False),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('transmissible', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.PrimaryKeyConstraint('doc_id', 'section')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corpus_chunks')
    # ### end Alembic commands ###
